### ISSUE TITLE
[FEATURE] Crear menú inicial para elegir dificultades

### ISSUE THREAD

**Issue by ColoOviedo** [JuampiCarosi/aninfo#5]
## 🚀 Feature

Crear un menu con distintas opciones para que el jugador pueda controlar el juego

### Motivation

Para poder iniciar el juego y elegir entre distintas dificultades

### Implementation

Debe ser previo a iniciar la partida y lo primero que se muestre al ejecutar el juego. 
Debe mostrar un mensaje de bienvenida y mostrar las opciones del menú de elección de dificultad que será el siguiente:
1) Facil
2) Normal
3) Dificil

Luego, debe pedir al jugador ingresar un número solo del 1 al 3. Al ingresar un número que no esté en ese rango se deberá mostrar un mensaje de error y volver a pedir un número.

Despues de seleccionar la dificultad deseada se debera iniciar el juego

**Comment by Tomas-NO** [comment]
Se resolvió en #32
